### ISSUE TITLE
Pretty printers are not loaded for Ada libraries

### ISSUE THREAD

**Issue by LordAro** [AdaCore/gnat-gdb-scripts#2]
As per https://github.com/AdaCore/gnat-gdb-scripts/blob/master/gnatdbg/__init__.py#L57, the pretty printers are only loaded when the object file contains the `(_)adainit` symbol.

Obviously, this is not present in dynamic library files, so the pretty printers do not work when debugging library code

Perhaps this filter should be amended to search for a wider set of symbols? Does it need to search for ada-specific symbols at all? I've hacked around it by replacing the `objfile_filter` with `return True`, and it doesn't appear to cause any issues

**Comment by pmderodat** [comment]
My intent for `objfile_filter` was to avoid adding all our generic pretty-printers for Ada to objfiles that don’t contain any Ada code, so that GDB wouldn’t spend time polling these when we’re sure that they’re not needed. I was afraid of introducing annoying delays when GDB prints values…

Indeed, as of today this means that we can’t pretty print-values for types coming from shared libraries (and many other cases). I don’t think there is a way to do this right anyway: at some point I looked for a way in GDB to check the languages coming with objfile debug info, but that’s not possible currently.

Maybe I should just bite the bullet and, by default, unconditionally register pretty-printers in GDB’s global list of pretty-printers. What I should probably do, however, would be to introduce a hook to load these pretty-printers whenever the shared library for libgnat is loaded (this is what GCC does for libstdc++ pretty-printers).

**Comment by pmderodat** [comment]
Hello,

This is now implemented! By default, `gnatdbg.setup` will register the pretty-printers for GNAT containers GDB-wide, so pretty-printing will trigger them even for shared libraries.
